### ISSUE TITLE
Exit with dedicated return code if no queries to run

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/sql-runner#105]
If e.g. the playbook is truncated, the pipeline completes with `0 queries run, 246ms`. Instead we should exit with a message ("no queries to run") and dedicated return code. The dedicated return code let's you treat no queries as a no-op should you so wish.

**Comment by miike** [comment]
What scenario/conditions would cause 0 queries to run (e.g., for a playbook to be truncated)?

**Comment by alexanderdean** [comment]
Playbook truncation due to error writing out e.g. a secret is a common one.
