### ISSUE TITLE
Add option to dump output

### ISSUE THREAD

**Issue by dilyand** [snowplow/sql-runner#107]
Currently jobs run with SQL Runner do not return any output. That's fine for queries that create permanent tables, views or delete data, etc; but limits the usage of the app to those cases.

**Comment by alexanderdean** [comment]
Can you give an example of a use case that is opened up by this ticket @dilyand?

**Comment by dilyand** [comment]
@alexanderdean Whenever we need to run SQL on a Redshift cluster we don't (and can't) have access to, we need to schedule a special joint session with TechOps. Usually, that can't be done in an async way because we need the output from one query to write the next one. That wastes TechOps time. If we could tell SQL Runner to dump the output, we can support clients with inaccessible Redshift clusters by running our queries as SQL Runner jobs using orchestration.

**Comment by alexanderdean** [comment]
Please update commit and CHANGELOG with new ticket name
