### ISSUE TITLE
Commented lines execute as empty SQL statements in Snowflake

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/sql-runner#119]
Strange bug - commented lines seem to be executed as individual "empty queries" in Snowflake.

This errors in Snowflake.

**Comment by BenFradet** [comment]
This is because of https://github.com/snowplow/sql-runner/blob/develop/sql_runner/snowflake_target.go#L60 since it seems we can only run sql statements one by one.

**Comment by alexanderdean** [comment]
Thanks for spotting that @BenFradet.

That implementation is going to play havoc with transactions.

Needs further thought.

**Comment by colmsnowplow** [comment]
Have come accross this bug, just adding a little more detail here. 

It seems that comments in-line don't produce the problem:

````
SELECT * FROM atomic.events -- Select all data
```

But comments at the end do:

```
SELECT * FROM atomic.events 

-- Select all data
```

Which leads me to believe that it could be addressed with validation per-query for whether or not any lines begin with a non-comment character?
