### ISSUE TITLE
Add ability to add variables on the command-line

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/sql-runner#12]
Useful for dynamic things such as dates.

**Comment by alexanderdean** [comment]
http://stackoverflow.com/questions/18115674/how-to-format-command-line-argument-key-value-pairs

**Comment by andrioni** [comment]
:+1:
I like the `--conf key1=val1 --conf key2=val2` way to do this, and just submitted a PR implementing it.

**Comment by alexanderdean** [comment]
Duplicate of #35 (PR), closing
