### ISSUE TITLE
Elide default Snowflake region in Target config

### ISSUE THREAD

**Issue by dilyand** [snowplow/sql-runner#121]
If a user is in the default Snowflake region, their login URL does not include the region name. That means we should leave that field empty in the playbook; or else get an error.

It would be better if we could just include the region variable, regardless; and if SQL Runner was smart enough to recognise the default region and elide it.

**Comment by chuwy** [comment]
Similar from loader https://github.com/snowplow-incubator/snowplow-snowflake-loader/commit/8772096b109aecdfe5c7c09bbb5a4f9328edf751#diff-db304e6da8e43e26f0786698596dc7c9R21
