### ISSUE TITLE
Add 'check SQL query' mode

### ISSUE THREAD

**Issue by dilyand** [snowplow/sql-runner#124]
With templated SQL queries, variables get replaced with values from the playbook.

```
:variables:
  :input_schema: atomic
```

and

```
SELECT * FROM {{.input_schema}}.events
```

produce:

```
SELECT * FROM atomic.events
```

With less straightforward cases, it will be helpful to check what value a variable get's replaced with, without having to go through the full Sync & Deploy & Run cycle.

One such case is:

```
:variables:
  :start_date: '2018-03-13'
```

where it isn't clear how the single quotes should be properly escaped.

**Comment by alexanderdean** [comment]
What should the output of 'check SQL query' mode be? How does this relate to `-dryRun`?

**Comment by dilyand** [comment]
The output should be the SQL query or queries the way they look after all the `{{.variables}}` have been replaced with values from the playbook. That will allow us to see the SQL that is going to actually be run.

Currently, a `-dryRun` of the playbook reports `SUCCESS` for the queries in it, but when we run the actual job it still might fail with a SQL error.

Since there is no visibility about the transformations that are being done to the variables, we have to debug this through trial and error; and a trial involves updating the file, waiting for S & D, asking Support to run the job manually, then waiting for the results. It's quite long-winded and can turn into a significant time-sink.

A 'check SQL option` would produce a SQL query that we can directly run in Redshift or Snowflake.

**Comment by alexanderdean** [comment]
Got it, I think we could go with with a CLI arg like `-fillTemplates` to kick this off.

**Comment by alexanderdean** [comment]
Updated ticket name, please update commit
