### ISSUE TITLE
Remove Wine from required playbooks

### ISSUE THREAD

**Issue by mhadam** [snowplow/sql-runner#129]
I couldn't find where Wine is used for this project - it takes a considerable amount of time in provisioning the Vagrant environment, so unless there's a use for it, it would be good to remove.

**Comment by BenFradet** [comment]
vagrant is unnecessary overhead for most projects including this one 👍

**Comment by mhadam** [comment]
@BenFradet regarding that, do you think I should transition the integration tests/scripts over to local development?

**Comment by BenFradet** [comment]
I know I don't use vagrant at all for dataflow-runner

**Comment by mhadam** [comment]
postgres is only required, I don't think that's very hard to have people run

**Comment by BenFradet** [comment]
if they're part of travis, people don't actually need to run them locally
