### ISSUE TITLE
Fix non-default Snowflake region from being invalidated

### ISSUE THREAD

**Issue by mhadam** [snowplow/sql-runner#134]
https://github.com/snowplow/sql-runner/blob/0.7.0/sql_runner/snowflake_target.go#L34

**Comment by alexanderdean** [comment]
I don't understand this one. What is the problem?

**Comment by alexanderdean** [comment]
Ouch! Scheduling.

**Comment by chuwy** [comment]
Just a heads-up that Azure is using slightly different host name. Could be useful to make sure we're able to use it https://github.com/snowplow-incubator/snowplow-snowflake-loader/issues/59

**Comment by mhadam** [comment]
@jbeemster @chuwy should we be matching against us-west-1? Because it seems like the default region used by Snowflake is us-west-2. Snowflake docs list US West (Oregon), and that matches with us-west-2 in the AWS docs.

https://docs.aws.amazon.com/general/latest/gr/rande.html
https://docs.snowflake.net/manuals/user-guide/intro-regions.html#region-ids-in-account-urls
