### ISSUE TITLE
README.md: Incorrect versions in the quickstart commands

### ISSUE THREAD

**Issue by palash25** [snowplow/sql-runner#139]
The readme mentions the following commands to download and run sql-runner
```
> wget http://dl.bintray.com/snowplow/snowplow-generic/sql_runner_0.7.1_linux_amd64.zip
> unzip sql_runner_0.8.0_linux_amd64.zip
```

I ran these and got the following error: 
`unzip:  cannot find or open sql_runner_0.8.0_linux_amd64.zip, sql_runner_0.8.0_linux_amd64.zip.zip or sql_runner_0.8.0_linux_amd64.zip.ZIP.`

Then I realised that both the commands had different versions of sql-runner mentioned and I was able to unzip it using 0.7.1 version.

If I am right about this I would like to send a PR to fix the README.

**Comment by BenFradet** [comment]
yes that's a mistake feel free to open a PR :+1:

**Comment by adatzer** [comment]
Closing as this has been fixed.
