### ISSUE TITLE
BigQuery: Unable to execute script with UDF

### ISSUE THREAD

**Issue by paulboocock** [snowplow/sql-runner#146]
**Affected Version:** `0.8.0`

**Description:** sql-runner is currently unable to run scripts against Google BigQuery that contain a User Defined Function (UDF).

An example UDF looks like:
```sql
CREATE TEMP FUNCTION
  multiply(x NUMERIC, y NUMERIC)  
  RETURNS NUMERIC  
  LANGUAGE js AS   
    '''  
        return x * y  
    ''';  
SELECT multiply(x,y) FROM (SELECT 2 AS x, 3 AS y);
```

The issue is caused due to the splitting of scripts in sql-runner that is done before each query is executed. The script is split on **;** but when specifying a UDF, the semi-colon is required before the next statement and the UDF must be followed by a query statement, so splitting the query into another API call doesn't work.
Trying to split the query into two separate calls results in the UDF returning:
`CREATE TEMPORARY FUNCTION statements must be followed by an actual query.`

The offending line of code is here:
https://github.com/snowplow/sql-runner/blob/a5b1481c3c8426591d7f6f42d7fa7ca66e2a97fa/sql_runner/bigquery_target.go#L75

Whilst I haven't tested this solution, the Google BigQuery documentation suggests when using the API that you can run multiple statements in a single API call as long as they are split by a semi-colon. Therefore I'm not sure the string splitting is actually required. See here: [Terminating Semicolons](https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#terminating-semicolons)
> You can optionally use a terminating semicolon (;) when you submit a query string statement through an Application Programming Interface (API).
> 
> In a request containing multiple statements, you must separate statements with semicolons, but the semicolon is generally optional after the final statement.

Another issue caused by splitting on semi-colon is that it's currently not possible to use semi-colons in a JavaScript UDF, as the script is split half way through the UDF. It's possible to work around this by removing semi-colons from the JS but I'm not able to find a way to work around the main issue listed above.

**Comment by colmsnowplow** [comment]
[Resolved](https://github.com/snowplow/sql-runner/commit/107e8aba5472833c7820f4425219eab4b9f2a7de)
