### ISSUE TITLE
Enable -sqlroot configuration via playbook

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/sql-runner#165]
Using the -sqlroot flag for local execution is more of a pain than it needs to be.

We could fix this by requiring only path to playbook, having that location be the working directory at runtime, and enabling configuration of a path to the sql files relative to that directory.

Alternatively we could impose a directory structure for sql-runner projects but it's less flexible that way.

**Comment by colmsnowplow** [comment]
In fact we don't even need to change working directory, we can just construct a path relative to the playbook path

**Comment by jbeemster** [comment]
It already has the option to use the playbook as the sqlroot:

> https://github.com/snowplow/sql-runner/blob/a24fc6e94bc4666e8234480ef3f1c947ff6a2ecc/sql_runner/main.go#L244-L248

You just define it with `-sqlroot PLAYBOOK` ... very badly documented but is that roughly what you were thinking?

**Comment by jbeemster** [comment]
In fact if you do not supply the `-sqlroot` argument it should default to PLAYBOOK already as per the docs.

```
-sqlroot string
    	Absolute path to SQL scripts. Use PLAYBOOK, BINARY and PLAYBOOK_CHILD for those respective paths (default "PLAYBOOK")
```

**Comment by colmsnowplow** [comment]
So what I was thinking of was the case where you have a directory structure something like this:

```
sql-runner
|
- sql
    - myfile.sql
- playbooks
    - myplaybook.yml
```

Which is a slightly different case to what we have already.

I _was_ thinking that we could set the sql-root to something like `PLAYBOOK/../sql/`, which won't work currently.

However I've just realised that I _hadn't_ tried setting the relative path in the `file` entry in the playbook steps themselves. Just gave that a test and it works! 

Closing this. Now I'm just upset I wasted so many valuable seconds fiddling with the `-sqlroot` path :D
