### ISSUE TITLE
Snowflake: convert query output to string before printing

### ISSUE THREAD

**Issue by dilyand** [snowplow/sql-runner#166]
When running `sql-runner ... --showQueryOutput` against a Snowflake target, the output is printed as a byte array instead of being stringified.

Possibly the change we need is:

```
func stringify(row []interface{}) []string {
	var line []string
	for _, element := range row {
		line = append(line, fmt.Sprint(element))
	}
	return line
}
```

to 

```
func stringify(row []interface{}) []string {
	var line []string
	for _, element := range row {
		line = append(line, fmt.Sprint(string(element)))
	}
	return line
}
```

Reference: https://yourbasic.org/golang/convert-string-to-byte-slice/

**Comment by colmsnowplow** [comment]
A quick bit of experimentation and it looks like we need something like this answer: https://stackoverflow.com/a/14500756

Each row of data will be of type *sql.RawBytes - we would need to iterate that and convert each element to string, then append that to `line`. 

Might need to implement an additional interface to do so.
