### ISSUE TITLE
BigQuery: Run multiple-step queries as single script

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/sql-runner#169]
I can't remember exactly why we [split scripts on semicolons](https://github.com/snowplow/sql-runner/blob/71117eca8f8f3a21c163c7acb36f269c3bbec504/sql_runner/bigquery_target.go#L75) in the original implementation, nor can I find a record of it. I think we were working around some issue.

This prevents us from using some pretty key functionality, like transactions and variables. For example:

```
BEGIN
  SELECT 1;
END;
```

and

```
DECLARE LOWER TIMESTAMP;

SET LOWER = (SELECT lower_limit FROM scratch.base_new_events_limits);

  -- Subset the manifest for performance.
CREATE OR REPLACE TABLE scratch.base_run_manifest
  AS(
    SELECT
      *

    FROM
      derived.base_event_id_manifest

    WHERE
      collector_tstamp >= LOWER
  );

END;
```

will both work perfectly fine using the BQ console, but won't work via SQL-runner.

Transactions are pretty important and variables are key to eliminating a huge amount of the complexity in our data models (table scans are not limited by subqueries but are limited by a variable that contains a query). 

I would say this is fairly essential functionality & we should find a way to instrument it ASAP. Hopefully simply removing the offending line would suffice.

**Comment by paulboocock** [comment]
This also caused issues for temp UDFs. See #146 - Potential fix in that ticket too.

**Comment by colmsnowplow** [comment]
A small bit of experimentation jogged my memory a bit - I believe the fix [here](https://github.com/snowplow/sql-runner/pull/170/commits/3883c000905588d01c2917606786098c64da4806) does indeed resolve it.

I had to update the BQ API to the latest version. This reminded me of why we split the script in the first place - I believe at the time there was an issue with multiple queries in a single script because the BQ go api expected each script to have a single output table. [This issue was fixed here](https://github.com/googleapis/google-cloud-go/commit/0ed376542baa8abb00e6b00050e8c711110b0518). I think we failed to pin down the true cause because [that issue caused the API to report an unhelpful error message](https://github.com/googleapis/google-cloud-go/issues/642). As far as I can remember we were pressed for resource and keen to release, so we split the script.

This fix also has the happy side effect of making query errors also more informative - both because the new API reports the underlying query error, and because the reported location of the error in the script now reflects the actual position in the sql file being executed (rather than position in the portion of the split script).

@jbeemster does this make sense to you and seem sensible? Would you have any input on what tests would be required to build confidence in this change? 

If you're happy with the approach I'd be keen to quickly roll out a release, as this would remove a roadblock on v1 BigQuery models. (The workarounds we've used previously are just not appropriate for a resilient model).

**Comment by colmsnowplow** [comment]
The above change seems to hide query failures from being returned. Would require a bit of digging to figure that out.
