### ISSUE TITLE
Add an environment variable function

### ISSUE THREAD

**Issue by andrioni** [snowplow/sql-runner#30]
It'd be nice to be able to support environment variables directly: it helps with the testing and reduces the chances of someone committing credentials :)

**Comment by alexanderdean** [comment]
Neat idea!

**Comment by alexanderdean** [comment]
This is less important given #35, but still nice

**Comment by jbeemster** [comment]
The priority here being:

* Load Env vars into variables map
* If present in playbook use playbook value
* If present in `-var` use that value

Is that right @alexanderdean ?

**Comment by alexanderdean** [comment]
Can't we just have a `systemEnv("foo")` function that checks to see if there is an environment variable available called "foo"?

**Comment by jbeemster** [comment]
We good as well yeah!  Does seem a bit saner than loading all of the environment variables into the application..
