### ISSUE TITLE
Upgrade vagrant push to upload OS X and Windows binaries

### ISSUE THREAD

**Issue by andrioni** [snowplow/sql-runner#31]
Do you think it'd possible to push OS X binaries, either to bintray or through the GitHub release mechanism? While I do think most users are going to deploy sql-runner on Linux, it's nice to be able to test on OS X without using Vagrant.

**Comment by alexanderdean** [comment]
Happy to do that if you can share a bash script for building on OS-X?

**Comment by andrioni** [comment]
Other than #29 (`godep go build` not working before a `go get github.com/snowplow/sql-runner`), `godep` works fine.

**Comment by andrioni** [comment]
The following works, even though it feels a little bit hackish.

```bash
#!/bin/bash
set -e

go get github.com/tools/godep
go get github.com/snowplow/sql-runner || true
$GOPATH/bin/godep go build
```

**Comment by alexanderdean** [comment]
Thanks!

**Comment by andrioni** [comment]
Also, Go 1.5 makes it really easy to cross-compile, but it launched a few weeks ago.

If you don't mind using Docker, it'd be really easy to run Go 1.5 on a container and build binaries for all platforms.

**Comment by andrioni** [comment]
[Done!](https://hub.docker.com/r/andrioni/sql-runner/)
For example, running the following command returns a 64-bit OS X binary on the directory `./dist`:
`docker run -v $(pwd)/dist:/dist -e GOOS=darwin -e GOARCH=amd64 -t andrioni/sql-runner`
