### ISSUE TITLE
Add ability to read playbook from Consul

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/sql-runner#43]

**Comment by jbeemster** [comment]
Could you expand on the exactly how this functionality should work @alexanderdean?

**Comment by jbeemster** [comment]
Notes:
* Client: https://github.com/hashicorp/consul/tree/master/api
* CLI Arg: `-consul http://localhost:8500`
* Get playbooks/sql from the Consul KV Store
  - https://www.consul.io/intro/getting-started/kv.html

**Comment by andrioni** [comment]
Although using the Consul Golang client is quite easier and probably more stable, a generic REST "playbook provider" would be an incredibly nice thing to have (although it might be borderline scope creep).

**Comment by alexanderdean** [comment]
Interesting idea @andrioni - feel free to create another ticket for this with how you think it could work!
