### ISSUE TITLE
Fix "panic: assignment to entry in nil map"

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/sql-runner#46]
Triggered when there is an issue with the supplied variables:

     panic: assignment to entry in nil map goroutine 1 [running]: github.com/snowplow/sql-runner/playbook.MergeCLIVariables(0xc8200e2400, 0x1, 0x1, 0x0, 0xc820118a00, 0xe, 0x10, 0xc8200dea20, 0x0, 0x0, ...) /opt/gopath/src/github.com/snowplow/sql-runner/playbook/playbook.go:49 +0x174 github.com/snowplow/sql-runner/playbook.ParsePlaybook(0x7fff43f6388f, 0x50, 0xc8200dea20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...) /opt/gopath/src/github.com/snowplow/sql-runner/playbook/playbook.go:42 +0x139 main.main() /opt/gopath/src/github.com/snowplow/sql-runner/main.go:38 +0x73 goroutine 17 [syscall, locked to thread]: runtime.goexit() /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 goroutine 5 [chan receive]: github.com/golang/glog.(*loggingT).flushDaemon(0xa83860) /opt/gopath/src/github.com/snowplow/sql-runner/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x67 created by github.com/golang/glog.init.1 /opt/gopath/src/github.com/snowplow/sql-runner/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297

**Comment by alexanderdean** [comment]
Ah, I believe the bug is when you pass -var in on the command-line but there are no variables in the playbook otherwise, so the variables map is empty...

**Comment by alexanderdean** [comment]
Confirmed that adding a dummy variable in the playbook fixes this:

```yaml
:variables:
  :workaround: for-issue-46
```

**Comment by andrioni** [comment]
Oops!

**Comment by alexanderdean** [comment]
Duplicate of #47
