### ISSUE TITLE
Add ability to set a lockfile for a run

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/sql-runner#54]
We often run SQL Runner inside a shell script which sets/checks a "run lock" to prevent the SQL Runner from starting if there was a problem completing the previous playbook run.

It would be nice to add this as a first class feature to SQL Runner, setting/checking the lock in Consul.

Proposal: two new CLI args:

```
* `-lock`     : Optional argument which checks and sets a lockfile to ensure this run is a singleton. Deletes lock on run completing successfully
* `-softLock` : Optional argument, like `-lock` but the lockfile will be deleted even if the run fails

#### More on Consul

Using the `-consul` argument results in the following changes:

* ...
* The `-lock` and `-softLock` arguments also become a key argument for Consul

If you pass in the default:

    ./sql-runner -consul "localhost:8500" -playbook "sql-runner/playbook/1" -lock "sql-runner/locks/1"

This results in:

* ...
* Checking and setting the lockfile at this key "sql-runner/locks/1"
```

**Comment by alexanderdean** [comment]
Bringing forwards...

**Comment by alexanderdean** [comment]
Some lock rules:

* If the lock file cannot be written, die with something like "Lock file $foo is not writable. Cannot start"
* If the lock file is already found, die with something like "SQL Runner $foo found, previous run failed or is ongoing. Cannot start"

**Comment by alexanderdean** [comment]
Note that the `-dryRun` should not check locks, nor set them...

**Comment by jbeemster** [comment]
What exit code would you like for lock file already found @alexanderdean ?

**Comment by alexanderdean** [comment]
Hmm, per http://tldp.org/LDP/abs/html/exitcodes.html maybe `3`?
