### ISSUE TITLE
Should the template function always be on rather than optional?

### ISSUE THREAD

**Issue by jbeemster** [snowplow/sql-runner#60]
The template function only does anything if there are macros to be templated, in which case you want it on.  Is there any reason why this should be switchable?

**Comment by alexanderdean** [comment]
I think the off switch is to protect against you having some really funky SQL which looks like it includes template macros but doesn't...

**Comment by jbeemster** [comment]
I thought it might have something to do with that.  If you have something like {{.randomFunkiness}} that does not have an available variable to fill it it will exception.

**Comment by jbeemster** [comment]
Closing this as the current situation is safer.
