### ISSUE TITLE
Investigate regression with SSL support

### ISSUE THREAD

**Issue by jbeemster** [snowplow/sql-runner#79]
http://discourse.snowplowanalytics.com/t/redshift-ssl-connection-resetting/891/3

**Comment by jbeemster** [comment]
Hey @alexanderdean so I have dug into this one:

1. I setup a fresh VPC and Redshift setup
2. I set `require_ssl` as true in the cluster Parameter Group

Attempting to run SQL against the cluster with `SSL: false` in the playbook:

```bash
vagrant@sql-runner:/opt/gopath/src/github.com/snowplow/sql-runner$ ./sql-runner -playbook dist/com.engineering/test-playbook.yml
2017/01/12 13:05:18 EXECUTING Create table: application_error_1 (in step Setup Tables @ com.engineering-main redshift database): /opt/gopath/src/github.com/snowplow/sql-runner/dist/com.engineering/queries/application_error_1.sql
2017/01/12 13:05:19 FAILURE: Create table: application_error_1 (step Setup Tables @ target com.engineering-main redshift database), ERROR: FATAL #28000 no pg_hba.conf entry for host "xxx.xxx.xxx.xxx", user "adminuser", database "snowplow", SSL off (addr="xxx.xxx.xxx.xxx:5439")
2017/01/12 13:05:19
TARGET INITIALIZATION FAILURES:
QUERY FAILURES:
* Query Create table: application_error_1 /opt/gopath/src/github.com/snowplow/sql-runner/dist/com.engineering/queries/application_error_1.sql (in step Setup Tables @ target com.engineering-main redshift database), ERROR:
  - FATAL #28000 no pg_hba.conf entry for host "xxx.xxx.xxx.xxx", user "adminuser", database "snowplow", SSL off (addr="xxx.xxx.xxx.xxx:5439")
```

Attempting to run SQL against the cluster with `SSL: true` in the playbook:

```bash
vagrant@sql-runner:/opt/gopath/src/github.com/snowplow/sql-runner$ ./sql-runner -playbook dist/com.engineering/test-playbook.yml
2017/01/12 13:05:08 EXECUTING Create table: application_error_1 (in step Setup Tables @ com.engineering-main redshift database): /opt/gopath/src/github.com/snowplow/sql-runner/dist/com.engineering/queries/application_error_1.sql
2017/01/12 13:05:10 SUCCESS: Create table: application_error_1 (step Setup Tables @ target com.engineering-main redshift database), ROWS AFFECTED: -1
2017/01/12 13:05:10 SUCCESS: 1 queries executed against 1 targets
```

In short everything appears to be working as expected without any code changes.

**Comment by alexanderdean** [comment]
Are you saying cannot reproduce?

**Comment by jbeemster** [comment]
Exactly - cannot reproduce.

**Comment by jbeemster** [comment]
Oh hang on!  On Ubuntu it works fine but I am getting the same error from the discourse thread on macOS..

**Comment by alexanderdean** [comment]
Okay - let's de-schedule this ticket and remove the milestone, and ask in Discourse for steps to reproduce...

**Comment by jbeemster** [comment]
Okay @alexanderdean it seems that the 0.5.1 build is producing some strange behaviour when it comes to SSL.  To test I downloaded the 0.5.1 Linux build which does indeed fail as reported.

This was built using GoLang 1.7.

The locally built version which uses GoLang 1.5 works as expected.

However we are in a bit of a tight spot as we need GoLang 1.7 to support macOS Sierra.

In short it doesn't look like it is a code issue but rather a compilation issue...

**Comment by alexanderdean** [comment]
Can we use different Golangs to build for different platforms?

**Comment by jbeemster** [comment]
I am hoping by jumping onto the latest GoLang version 1.7.4 rather than 1.7 we can get this fixed.  There seem to be a bunch of updates around networking:

> go1.7.1 (released 2016/09/07) includes fixes to the compiler, runtime, documentation, and the compress/flate, hash/crc32, io, net, net/http, path/filepath, reflect, and syscall packages. See the Go 1.7.1 milestone on our issue tracker for details.

> go1.7.2 should not be used. It was tagged but not fully released. The release was deferred due to a last minute bug report. Use go1.7.3 instead, and refer to the summary of changes below.

> go1.7.3 (released 2016/10/19) includes fixes to the compiler, runtime, and the crypto/cipher, crypto/tls, net/http, and strings packages. See the Go 1.7.3 milestone on our issue tracker for details.

> go1.7.4 (released 2016/12/01) includes two security fixes. See the Go 1.7.4 milestone on our issue tracker for details

So hopefully if we build on 1.7.4 everything should resolve itself.

**Comment by mialberhasky** [comment]
I just double-checked, and I'm getting the error from both the 2016.09 and 2016.09.1 releases on Amazon Linux against sql-runner 0.5.1. I also confirmed that on my Mac (10.11.6), 0.4.0 of the sql-runner works with SSL, while 0.5.1 does not.

-Michael

**Comment by jbeemster** [comment]
So I have just setup Go 1.7.4 and re-downloaded all of the dependencies.  We are now getting a new error:

```bash
vagrant@sql-runner:/opt/gopath/src/github.com/snowplow/sql-runner$ ./sql-runner -playbook dist/com.engineering/test-playbook.yml
2017/01/12 14:58:29 EXECUTING Create table: application_error_1 (in step Setup Tables @ com.engineering-main redshift database): /opt/gopath/src/github.com/snowplow/sql-runner/dist/com.engineering/queries/application_error_1.sql
2017/01/12 14:58:39 FAILURE: Create table: application_error_1 (step Setup Tables @ target com.engineering-main redshift database), ERROR: dial tcp xxx.xxx.xxx.xxx:5439: i/o timeout
2017/01/12 14:58:39
TARGET INITIALIZATION FAILURES:
QUERY FAILURES:
* Query Create table: application_error_1 /opt/gopath/src/github.com/snowplow/sql-runner/dist/com.engineering/queries/application_error_1.sql (in step Setup Tables @ target com.engineering-main redshift database), ERROR:
  - dial tcp xxx.xxx.xxx.xxx:5439: i/o timeout
```

Will do a more bit more digging into why this one is happening but if I cannot resolve will revert to Go 1.5 and temporarily drop support for macOS Sierra...

**Comment by alexanderdean** [comment]
SGTM!

**Comment by jbeemster** [comment]
Okay so did some more digging; turns out that the version of Postgres I had was actually the problem in the end.  Downgrading back to pg.v4 has resolved the connection error.  The exact same TLS settings are being applied to both versions so something else has to be at play here.

I have opened a bug to track this but in the meantime we will need to drop back to pg.v4 to get TLS to work again.

However this means that we lose the TCP KeepAlive that we needed pg.v5 for in the first place!

@alexanderdean am I okay to revert this functionality and to create a new ticket to add it back once pg.v5 has stabilised?

**Comment by alexanderdean** [comment]
Yes - go for it @jbeemster !

**Comment by jbeemster** [comment]
This issue has been fixed in the pg library so we can close this!
