### ISSUE TITLE
Add tcpKeepAlive=true for long-running queries via NAT

### ISSUE THREAD

**Issue by jbeemster** [snowplow/sql-runner#87]
This had to be removed as part of a regression issue with upgrading the underlying Postgres library.

Code snippet for this:

https://github.com/snowplow/sql-runner/blob/0.5.1/sql_runner/postgres_target.go#L33-L59

**Comment by alexanderdean** [comment]
We need an accompanying ticket in the impending release where we remove this feature, otherwise the CHANGELOG will look like we are adding the same feature twice...

**Comment by jbeemster** [comment]
No longer required as maintainer of pg has fixed SSL issue.
